
spring:
  datasource:
    url: 
    username:
    password: 
    driver-class-name: 

  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

appconfig:
  imgPath: C:\Data\GSICS\icvs\image_test